#include "lexical_analyzer.h"

const char* strtoken(Token t) {
    switch (t) {
        case ERROR:
            return "ERROR";
        case ADD:
            return "ADD";
        case SUB:
            return "SUB";
        case MUL:
            return "MUL";
        case DIV:
            return "DIV";
        case LT:
            return "LT";
        case LTE:
            return "LTE";
        case GT:
            return "GT";
        case GTE:
            return "GTE";
        case EQ:
            return "EQ";
        case NEQ:
            return "NEQ";
        case ASSIN:
            return "ASSIN";
        case SEMICOLON:
            return "SEMICOLON";
        case COMMA:
            return "COMMA";
        case LPARENTHESE:
            return "LPARENTHESE";
        case RPARENTHESE:
            return "RPARENTHESE";
        case LBRACKET:
            return "LBRACKET";
        case RBRACKET:
            return "RBRACKET";
        case LBRACE:
            return "LBRACE";
        case RBRACE:
            return "RBRACE";
        case ELSE:
            return "ELSE";
        case IF:
            return "IF";
        case INT:
            return "INT";
        case RETURN:
            return "RETURN";
        case VOID:
            return "VOID";
        case WHILE:
            return "WHILE";
        case IDENTIFIER:
            return "IDENTIFIER";
        case NUMBER:
            return "NUMBER";
        case LETTER:
            return "LETTER";
        case ARRAY:
            return "ARRAY";
        case EOL:
            return "EOL";
        case COMMENT:
            return "COMMENT";
        case BLANK:
            return "BLANK";
    }
}

const char* actual_token_str(Token t) {
    switch (t) {
        case ADD:
            return "+";
        case SUB:
            return "-";
        case MUL:
            return "*";
        case DIV:
            return "/";
        case LT:
            return "<";
        case LTE:
            return "<=";
        case GT:
            return ">";
        case GTE:
            return ">=";
        case EQ:
            return "==";
        case NEQ:
            return "!=";
        case ASSIN:
            return "=";
        case SEMICOLON:
            return ";";
        case COMMA:
            return ",";
        case LPARENTHESE:
            return "(";
        case RPARENTHESE:
            return ")";
        case LBRACKET:
            return "[";
        case RBRACKET:
            return "]";
        case LBRACE:
            return "{";
        case RBRACE:
            return "}";
        case ELSE:
            return "else";
        case IF:
            return "if";
        case INT:
            return "int";
        case RETURN:
            return "return";
        case VOID:
            return "void";
        case WHILE:
            return "while";
        case ARRAY:
            return "[]";
    }
}